kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../../../common/cert-manager/certificates/

patches: 
  - target:
      kind: Certificate
      name: openshift-api
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - api.ocp4.ypolat.me
  - target:
      kind: APIServer
      name: cluster
    patch: |-
      - op: replace
        path: /spec/servingCerts/namedCertificates/0/names
        value:
          - api.ocp4.ypolat.me
  - target:
      kind: Certificate
      name: openshift-wildcard
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - "*.apps.ocp4.ypolat.me"
      - op: replace
        path: /spec/commonName
        value: "*.apps.ocp4.ypolat.me"