apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - route.yaml

helmCharts:
  - name: vault
    version: 0.23.0
    repo: https://helm.releases.hashicorp.com
    namespace: hashicorp-vault
    releaseName: hashicorp-vault
    includeCRDs: true
    valuesInline:
      global:
        openshift: true
      ui:
        enable: true