apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-api
  namespace: openshift-config
spec:
  secretName: openshift-api-certificate
  issuerRef:
    name: letsencrpyt-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - 