apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../common/cert-manager/instance/

secretGenerator:
  - name: cloudflare-api-token-secret
    namespace: openshift-cert-manager
    files:
      - api-token=cloudflare-api-token-secret.yaml
    options:
      disableNameSuffixHash: true