apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-config
  source:
    path: clusters/default/external-secrets/operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: openshift-operators
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true