apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ingress-certificate
    namespace: openshift-ingress
    type: "kubernetes.io/tls"
    files:
      - tls.crt=tls-ingress.crt
      - tls.key=tls-ingress.key

bases:
  - ../../../../common/baseconfig/ingress-controller

patches:
  - target:
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    patch: |-
      - op: replace
        path: /spec/defaultCertificate/name
        value: 'apps.ocp4.ypolat.me'
      - op: replace
        path: /spec/domain
        value: 'apps.ocp4.ypolat.me'
      - op: replace
        path: /spec/replicas
        value: 3
