apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../common/external-secrets/operator/

patches:
  - target:
      kind: Subscription
      name: external-secrets-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'