apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrpyt-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yigitpolatt@gmail.com
    privateKeySecretRef:
      name: letsencrpyt-clusterissuer-secret
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret